# Generated by Django 5.2.12 on 2026-04-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО / группа')),
                ('answers', models.JSONField(default=dict, verbose_name='Ответы (JSON)')),
                ('score_part1', models.PositiveSmallIntegerField(default=0)),
                ('score_part2', models.PositiveSmallIntegerField(default=0)),
                ('score_part3', models.PositiveSmallIntegerField(default=0)),
                ('score_auto_total', models.PositiveSmallIntegerField(default=0)),
                ('grading_detail', models.JSONField(blank=True, default=dict, verbose_name='Детали автопроверки')),
                ('score_part4', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Баллы за часть 4 (вручную)')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сдача',
                'verbose_name_plural': 'Сдачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
