# Generated by Django 5.2.12 on 2026-04-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='variant',
            field=models.CharField(db_index=True, default='v1', help_text='v1 / v2 / v3 — какой набор вопросов был на экране', max_length=8, verbose_name='Билет'),
        ),
    ]
