# Generated by Django 5.2.12 on 2026-04-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_submission_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=48, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('variant', models.CharField(blank=True, default='', max_length=8)),
                ('page', models.CharField(default='test', max_length=16)),
            ],
            options={
                'verbose_name': 'Присутствие',
                'verbose_name_plural': 'Присутствия',
            },
        ),
    ]
