# Generated by Django 5.2.12 on 2026-04-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='clipboard_used',
            field=models.BooleanField(default=False, verbose_name='Было копирование на экране теста'),
        ),
        migrations.AddField(
            model_name='submission',
            name='clipboard_used',
            field=models.BooleanField(default=False, verbose_name='Копирование на экране теста'),
        ),
    ]
